src/Entity/Dto/FileDto.php
<?php

namespace CodeBuds\EasyAdminLogViewerBundle\Entity\Dto;

use CodeBuds\EasyAdminLogViewerBundle\Service\LogFileService;

class FileDto
{
    private string $name;

    private string $path;

    private ?int $size = null;

    private ?\DateTime $lastUpdatedAt = null;

    public function getHumanSize(): string
    {
        return LogFileService::humanFilesize($this->size);
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPath(): string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(?int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getLastUpdatedAt(): ?\DateTime
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?\DateTime $lastUpdatedAt): self
    {
        $this->lastUpdatedAt = $lastUpdatedAt;

        return $this;
    }
}

src/Entity/Dto/LogFileLine.php
<?php

namespace CodeBuds\EasyAdminLogViewerBundle\Entity\Dto;

class LogFileLine
{
    private string $type;

    private string $level;

    private string $badgeLevel;

    private ?\DateTime $date;

    private ?string $message;

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLevel(): string
    {
        return $this->level;
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getBadgeLevel(): string
    {
        return $this->badgeLevel;
    }

    public function setBadgeLevel(string $badgeLevel): self
    {
        $this->badgeLevel = $badgeLevel;

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(?\DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = $message;

        return $this;
    }
}

src/Controller/Admin/LogFileController.php
<?php

namespace CodeBuds\EasyAdminLogViewerBundle\Controller\Admin;

use CodeBuds\EasyAdminLogViewerBundle\Service\LogFileService;
use EasyCorp\Bundle\EasyAdminBundle\Config\Option\EA;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class LogFileController extends AbstractController
{
    public function __construct(
        private readonly LogFileService    $logFileService,
        private readonly AdminUrlGenerator $adminUrlGenerator,
    ) {
    }

    public function list(): Response
    {
        $files = $this->logFileService->getLogFiles();

        return $this->render('@EasyAdminLogViewer/list.html.twig', [
            'files' => $files,
        ]);
    }

    public function download(Request $request): Response
    {
        $routeParams = $request->query->all()[EA::ROUTE_PARAMS];
        $path = $routeParams['path'];

        if (!$this->isGranted('ROLE_ADMIN')) {
            throw new AccessDeniedException();
        }

        $this->logFileService->validateLogFilePath($path);

        // Validate that the file exists before creating the response
        if (!file_exists($path)) {
            throw $this->createNotFoundException('The file does not exist.');
        }

        $response = new BinaryFileResponse($path);
        // You can set whatever Content-Type you like, depending on the type of file you're sending
        $response->headers->set('Content-Type', 'text/plain');
        $response->setContentDisposition(
            ResponseHeaderBag::DISPOSITION_ATTACHMENT,
            basename($path),  // This will set the downloaded file's name
        );

        return $response;
    }

    public function show(Request $request): Response
    {
        $routeParams = $request->query->all()[EA::ROUTE_PARAMS];
        $path = $routeParams['path'];

        $file = $this->logFileService->getFileDataForAbsolutePath($path);

        if (!$this->isGranted('ROLE_ADMIN')) {
            throw new AccessDeniedException();
        }

        return $this->render('@EasyAdminLogViewer/show.html.twig', [
            'file' => $file,
        ]);
    }

    public function delete(Request $request): RedirectResponse
    {
        $routeParams = $request->query->all()[EA::ROUTE_PARAMS];
        $path = $routeParams['path'];

        if (!$this->isGranted('ROLE_ADMIN')) {
            throw new AccessDeniedException();
        }

        $type = 'success';

        try {
            $this->logFileService->validateLogFilePath($path);
            $message = $this->logFileService->deleteLogFile($path);
        } catch (\Exception $exception) {
            $type = 'error';
            $message = $exception->getMessage();
        }

        $this->addFlash($type, $message);

        $url = $this->adminUrlGenerator->setRoute('easy_admin_log_viewer_list')->generateUrl();

        return new RedirectResponse($url);
    }
}

templates/components/Lines.html.twig
{% for line in lines %}
	<div style="display: flex; gap: 2rem">
		<span>{{ line.date|format_datetime() }}</span>
		<span>{{ line.type }}</span>
		<b>
				<span class="badge badge-{{ line.badgeLevel }}">
					{{- line.level -}}
				</span>
		</b>
	</div>
	<div style="overflow-wrap: break-word;">
		{{ line.message }}
	</div>
	<hr/>
{% endfor %}

templates/components/Show.html.twig
<div {{ attributes }}>
	<label>
		<span>Level</span>
		<select class="form-select" name="levelFilter" data-model="level" data-action="live#action"
						data-live-action-param="changeFilter">
			<option {% if level is null %} selected {% endif %} value="">All</option>
			{% for levelFilter in levelFilters %}
				<option {% if level == levelFilter %} selected {% endif %} value="{{ levelFilter }}">{{ levelFilter }}</option>
			{% endfor %}
		</select>
	</label>
	<label>
		<span>Type</span>
		<select class="form-select" name="typeFilter" data-model="type" data-action="live#action"
						data-live-action-param="changeFilter">
			<option {% if type is null %} selected {% endif %} value="">All</option>
			{% for typeFilter in typeFilters %}
				<option {% if type == typeFilter %} selected {% endif %} value="{{ typeFilter }}">{{ typeFilter }}</option>
			{% endfor %}
		</select>
	</label>

	<span>
		Lines <span class="badge badge-primary">{{ lineCount }}</span>
	</span>

	<br>
	<br>


	<twig:EasyAdminLogViewer:Lines :lines="contentArray"/>
</div>

templates/components/admin_log_viewer/Show.html.twig
<div {{ attributes }}>
	<label>
		<span>Level</span>
		<select class="form-select" name="levelFilter" data-model="level" data-action="live#action"
						data-live-action-param="changeFilter">
			<option {% if level is null %} selected {% endif %} value="">All</option>
			{% for levelFilter in levelFilters %}
				<option {% if level == levelFilter %} selected {% endif %} value="{{ levelFilter }}">{{ levelFilter }}</option>
			{% endfor %}
		</select>
	</label>
	<label>
		<span>Type</span>
		<select class="form-select" name="typeFilter" data-model="type" data-action="live#action"
						data-live-action-param="changeFilter">
			<option {% if type is null %} selected {% endif %} value="">All</option>
			{% for typeFilter in typeFilters %}
				<option {% if type == typeFilter %} selected {% endif %} value="{{ typeFilter }}">{{ typeFilter }}</option>
			{% endfor %}
		</select>
	</label>

	<span>
		Lines <span class="badge badge-primary">{{ lineCount }}</span>
	</span>

	<br>
	<br>


	<twig:AdminLogViewer:Lines :lines="contentArray"/>
</div>

templates/list.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}

{% block page_title 'Log files' %}
{% block page_content %}
	<table class="table datagrid {% if files is empty %}datagrid-empty{% endif %}">
		<thead>
		<tr>
			<th class="header-for-field-text">Name</th>
			<th class="header-for-field-text">Size</th>
			<th class="header-for-field-text">Path</th>
			<th class="header-for-field-text">UpdatedOn</th>
			<th></th>
		</tr>
		</thead>
		<tbody>
		{% for file in files %}
			<tr>
				<td><a href="{{ ea_url().setRoute('easy_admin_log_viewer_download', {path: file.path}) }}">{{ file.name }}</a></td>
				<td>{{ file.humanSize }}</td>
				<td>{{ file.path }}</td>
				<td>{{ file.lastUpdatedAt|format_datetime() }}</td>
				<td class="actions">
					<a class="action"
						 href="{{ ea_url().setRoute('easy_admin_log_viewer_show', {path: file.path}) }}" ><span class="action-label">Show</span></a>

					<a class="action text-danger"
						 href="{{ ea_url().setRoute('easy_admin_log_viewer_delete', {path: file.path}) }}" ><span class="action-label">Delete</span></a>
				</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>

{% endblock %}

templates/show.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}

{% block page_title %}
	{{ file.name }} <small> size : {{ file.humanSize }}    last updated : {{ file.lastUpdatedAt|format_datetime }}</small>
{% endblock %}
{% block page_actions %}
	<div class="page-actions" style="display: flex; gap: 2rem">
		<a href="{{ ea_url().setRoute('easy_admin_log_viewer_list') }}">
			<button class="btn btn-primary">
				<span class="btn-label"><span class="action-label">Return to list</span></span>
			</button>
		</a>

		<a href="{{ ea_url().setRoute('easy_admin_log_viewer_download', {path: file.path}) }}">
			<button class="btn btn-secondary">
				<span class="btn-label"><span class="action-label">Download</span></span>
			</button>
		</a>

		<a href="{{ ea_url().setRoute('easy_admin_log_viewer_delete', {path: file.path}) }}">
			<button class="btn btn-danger">
				<span class="btn-label"><span class="action-label">Delete</span></span>
			</button>
		</a>

		<a href="{{ ea_url().setRoute('easy_admin_log_viewer_show', {path: file.path}) }}">
			<button class="btn btn-secondary">
				<span class="btn-label"><span class="action-label">Reload</span></span>
			</button>
		</a>
	</div>

{% endblock %}
{% block page_content %}

	<twig:EasyAdminLogViewer:Show :file="file" />

{% endblock %}